name: 'Aws Terraform'

on:
  push:
    branches:
    paths:
      - 'aws/**'
      - '.github/workflows/pipeline-aws.yml'
  pull_request:
    paths:
      - 'aws/**'
      - '.github/workflows/pipeline-aws.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_WORKSPACE: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}

defaults:
  run:
    shell: bash
    working-directory: ./aws

jobs:

  lint_and_validate:
    name: "Lint and validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Install TFLint
        run: |
          curl -sSL https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/
          tflint --version

      - name: Terraform fmt check
        run: terraform fmt -check

      - name: TFLint linting
        run: tflint --recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

  security_scan:
    name: "Scan Resources"
    runs-on: ubuntu-latest
    needs: lint_and_validate

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      - name: Checkov security scan
        run: checkov -d ./aws

  plan:
    name: "Plan aws Resources"
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

  apply:
    name: 'Apply aws Resources'
    runs-on: ubuntu-latest
    needs: plan
    environment: production
    if: github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
